# exploratory data analysis (EDA)

In [1]:
import pandas as pd

In [14]:
df = pd.read_csv('/home/carolina/lgcm/dev/dvc-in-action/data/data.csv')

In [15]:
print("Dimensões do dataset:", df.shape)
print("\nVisualizar as primeiras linhas:")
df.head()

Dimensões do dataset: (10000, 21)

Visualizar as primeiras linhas:

,Id,PostTypeId,AcceptedAnswerId,CreationDate,Score,ViewCount,Body,OwnerUserId,LastEditorUserId,LastEditorDisplayName,...,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,CommunityOwnedDate,ContentLicense,OwnerDisplayName,ClosedDate
0,4,1,7.0,2008-07-31T21:42:52.667,756,63468,<p>I want to use a <code>Track-Bar</code> to c...,8.0,3072350.0,Rich B,...,2021-11-15T21:15:29.713,How to convert a Decimal to a Double in C#?,<c#><floating-point><type-conversion><double><...,12,4,59.0,2012-10-31T16:42:47.213,CC BY-SA 4.0,NaN,NaN
1,77434,1,NaN,2008-09-16T21:40:29.927,335,416570,<p>Suppose I have a vector that is nested in a...,14008.0,3768871.0,NaN,...,2019-07-31T05:17:56.340,How to access the last value in a vector?,<r><dataframe><vector>,11,3,70.0,NaN,CC BY-SA 3.0,NaN,NaN
2,6,1,31.0,2008-07-31T22:08:08.620,313,22477,<p>I have an absolutely positioned <code>div</...,9.0,9134576.0,user14723686,...,2021-01-29T18:46:45.963,Why did the width collapse in the percentage w...,<html><css><internet-explorer-7>,7,0,13.0,NaN,CC BY-SA 4.0,NaN,NaN
3,79709,1,NaN,2008-09-17T03:39:16.913,5,974,<p>I have a function inside a loop inside a fu...,NaN,202229.0,NaN,...,2016-04-28T13:21:33.607,Worse sin: side effects or passing massive obj...,<memory><r><function><global-variables><side-e...,7,2,2.0,NaN,CC BY-SA 3.0,James Lavin,NaN
4,9,1,1404.0,2008-07-31T23:40:59.743,2099,725914,<p>Given a <code>DateTime</code> representing ...,1.0,6537157.0,Rich B,...,2022-02-19T14:25:44.773,How do I calculate someone's age based on a Da...,<c#><.net><datetime>,70,10,484.0,2011-08-16T19:40:43.080,CC BY-SA 4.0,NaN,NaN

In [24]:
print("\nProporção de valores nulos por coluna:")
print((df.isnull().sum() / len(df)) * 100)

Proporção de valores nulos por coluna:
PostTypeId           0.00
AcceptedAnswerId     0.00
CreationDate         0.00
Score                0.00
ViewCount            0.00
Body                 0.00
LastEditDate        21.22
LastActivityDate     0.00
Title                0.00
Tags                 0.01
AnswerCount          0.00
CommentCount         0.00
FavoriteCount       28.14
CreationYear         0.00
CreationMonth        0.00
CreationDay          0.00
dtype: float64

In [17]:
limite_nulos = 0.6
colunas_para_remover = df.columns[df.isnull().mean() > limite_nulos]

# Exibir as colunas que serão removidas
print("\nColunas com mais de 60% de nulos:")
print(colunas_para_remover)

# Remover as colunas com muitos nulos
df = df.drop(columns=colunas_para_remover)

Colunas com mais de 60% de nulos:
Index(['LastEditorDisplayName', 'CommunityOwnedDate', 'ClosedDate'], dtype='object')

In [18]:
# colunas menos importantes (baseado em entendimento do dataset)
colunas_irrelevantes = ['Id', 'ContentLicense', 'OwnerDisplayName','OwnerUserId','LastEditorUserId']
colunas_para_remover = [col for col in colunas_irrelevantes if col in df.columns]

print("\nColunas irrelevantes:")
print(colunas_para_remover)

# Remover colunas irrelevantes
df = df.drop(columns=colunas_para_remover)

Colunas irrelevantes:
['Id', 'ContentLicense', 'OwnerDisplayName', 'OwnerUserId', 'LastEditorUserId']

In [23]:
df.head()

,PostTypeId,AcceptedAnswerId,CreationDate,Score,ViewCount,Body,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,CreationYear,CreationMonth,CreationDay
0,1,7.0,2008-07-31 21:42:52.667,756,63468,<p>I want to use a <code>Track-Bar</code> to c...,2021-02-26 03:31:15.027,2021-11-15 21:15:29.713,How to convert a Decimal to a Double in C#?,"[c#, floating-point, type-conversion, double, ...",12,4,59.0,2008,7,31
1,1,0.0,2008-09-16 21:40:29.927,335,416570,<p>Suppose I have a vector that is nested in a...,2019-04-29 03:29:16.023,2019-07-31 05:17:56.340,How to access the last value in a vector?,"[r, dataframe, vector, ]",11,3,70.0,2008,9,16
2,1,31.0,2008-07-31 22:08:08.620,313,22477,<p>I have an absolutely positioned <code>div</...,2021-01-29 18:46:45.963,2021-01-29 18:46:45.963,Why did the width collapse in the percentage w...,"[html, css, internet-explorer-7, ]",7,0,13.0,2008,7,31
3,1,0.0,2008-09-17 03:39:16.913,5,974,<p>I have a function inside a loop inside a fu...,2016-04-28 13:21:33.607,2016-04-28 13:21:33.607,Worse sin: side effects or passing massive obj...,"[memory, r, function, global-variables, side-e...",7,2,2.0,2008,9,17
4,1,1404.0,2008-07-31 23:40:59.743,2099,725914,<p>Given a <code>DateTime</code> representing ...,2021-01-05 17:33:32.393,2022-02-19 14:25:44.773,How do I calculate someone's age based on a Da...,"[c#, .net, datetime, ]",70,10,484.0,2008,7,31

In [20]:
#tratar nulos da coluna de respostas aceitas e transformar em zeros 
df['AcceptedAnswerId'] = df['AcceptedAnswerId'].fillna(0)

In [21]:
# Converter colunas de data para datetime
datas = ['CreationDate', 'LastEditDate', 'LastActivityDate']
for coluna in datas:
    df[coluna] = pd.to_datetime(df[coluna])

## Criar novas features baseadas nas datas
df['CreationYear'] = df['CreationDate'].dt.year
df['CreationMonth'] = df['CreationDate'].dt.month
df['CreationDay'] = df['CreationDate'].dt.day

In [22]:
# Remover os '<>' e transformar em listas
df['Tags'] = df['Tags'].str.replace('<', '').str.split('>')[:-1]

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PostTypeId        10000 non-null  int64
 1   AcceptedAnswerId  10000 non-null  float64
 2   CreationDate      10000 non-null  datetime64[ns]
 3   Score             10000 non-null  int64
 4   ViewCount         10000 non-null  int64
 5   Body              10000 non-null  object
 6   LastEditDate      7878 non-null   datetime64[ns]
 7   LastActivityDate  10000 non-null  datetime64[ns]
 8   Title             10000 non-null  object
 9   Tags              9999 non-null   object
 10  AnswerCount       10000 non-null  int64
 11  CommentCount      10000 non-null  int64
 12  FavoriteCount     7186 non-null   float64
 13  CreationYear      10000 non-null  int32
 14  CreationMonth     10000 non-null  int32
 15  CreationDay       10000 non-null  int32
dtypes: datetime64[ns](3), float64(2), int32(3), int64(5), object(3)
memory usage: 1.1+ MB

In [28]:
df

,PostTypeId,AcceptedAnswerId,CreationDate,Score,ViewCount,Body,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,CreationYear,CreationMonth,CreationDay
0,1,7.0,2008-07-31 21:42:52.667,756,63468,<p>I want to use a <code>Track-Bar</code> to c...,2021-02-26 03:31:15.027,2021-11-15 21:15:29.713,How to convert a Decimal to a Double in C#?,"[c#, floating-point, type-conversion, double, ...",12,4,59.0,2008,7,31
1,1,0.0,2008-09-16 21:40:29.927,335,416570,<p>Suppose I have a vector that is nested in a...,2019-04-29 03:29:16.023,2019-07-31 05:17:56.340,How to access the last value in a vector?,"[r, dataframe, vector, ]",11,3,70.0,2008,9,16
2,1,31.0,2008-07-31 22:08:08.620,313,22477,<p>I have an absolutely positioned <code>div</...,2021-01-29 18:46:45.963,2021-01-29 18:46:45.963,Why did the width collapse in the percentage w...,"[html, css, internet-explorer-7, ]",7,0,13.0,2008,7,31
3,1,0.0,2008-09-17 03:39:16.913,5,974,<p>I have a function inside a loop inside a fu...,2016-04-28 13:21:33.607,2016-04-28 13:21:33.607,Worse sin: side effects or passing massive obj...,"[memory, r, function, global-variables, side-e...",7,2,2.0,2008,9,17
4,1,1404.0,2008-07-31 23:40:59.743,2099,725914,<p>Given a <code>DateTime</code> representing ...,2021-01-05 17:33:32.393,2022-02-19 14:25:44.773,How do I calculate someone's age based on a Da...,"[c#, .net, datetime, ]",70,10,484.0,2008,7,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1,0.0,2008-09-15 05:33:09.153,2,5135,<p>In Hibernate we have two classes with the f...,2008-09-23 10:40:44.420,2018-12-20 13:54:33.710,Lazy loading property and session.get problem,"[java, hibernate, lazy-loading, ]",5,0,1.0,2008,9,15
9996,1,0.0,2011-01-28 18:59:23.837,1,918,<p>I'm doing some statistical processing of ex...,2015-12-03 21:36:05.177,2015-12-03 21:36:05.177,How to consolidate multiple data series in R,"[r, statistics, ]",3,0,1.0,2011,1,28
9997,1,4841996.0,2011-01-28 20:08:06.067,21,25551,<p>I'm trying to get R (running on Windows) to...,2011-01-28 20:18:30.743,2018-05-03 18:57:07.180,How do I tell the R interpreter how to use the...,"[r, proxy, ]",3,4,12.0,2011,1,28
9998,1,62239.0,2008-09-15 05:47:37.340,1,399,<p>I'm looking for a control that the Visual S...,2012-05-03 15:21:10.110,2012-05-03 15:21:10.110,VS 2005 Toolbox kind of control .NET,"[c#, c++, .net, vb.net, visual-studio-2005, ]",3,0,NaN,2008,9,15
9999,1,4878090.0,2008-09-15 06:07:05.687,2,364,<p>I use more than one machine for development...,2008-09-15 07:30:09.043,2011-02-02 18:05:19.283,VS Code Snippets automatic synchronizer?,NaN,6,0,NaN,2008,9,15

In [ ]:
#df.to_csv("/home/carolina/lgcm/dev/dvc-in-action/data/processed_data.csv", index=False)